language: node_js
node_js:
- '0.11'
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - npm install bower
  - bower install --config.cwd=app/
script:
  - npm run mocha-main
  - npm run mocha-renderer
